# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: false

r: devel
  
cran: http://cran.stat.ucla.edu

r_packages: 
  - knitr
  - rmarkdown
  
r_github_packages: thibautjombart/apex

apt_packages:
  - libgsl-dev

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh

install:
  - ./travis-tool.sh aptget_install libgsl0-dev
  - ./travis-tool.sh install_deps
