# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: 
  - devel

sudo: false
# dist: trusty
cran: http://cran.at.r-project.org
cache: packages
warnings_are_errors: false

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages: 
  - knitr
  - rmarkdown

addons:
  apt:
    packages:
      - libgsl0-dev
      - libudunits2-dev
      - libcurl4-openssl-dev      
      - gdal-bin
      - libgdal1-dev

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh