# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: 
  - devel

sudo: false
cran: http://cran.at.r-project.org
cache: packages
warnings_are_errors: false

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

r_packages: 
  - knitr
  - rmarkdown
  
r_github_packages: 
  - thibautjombart/apex

apt_packages:
  - libgsl-dev
