# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

indGenotype <- function(nInd, numAlleles, locus) {
    .Call('strataGdevel_indGenotype', PACKAGE = 'strataGdevel', nInd, numAlleles, locus)
}

HoCalc <- function(nInd, loci, ploidy, strata, strataN) {
    .Call('strataGdevel_HoCalc', PACKAGE = 'strataGdevel', nInd, loci, ploidy, strata, strataN)
}

HsCalc <- function(alleleFreq, ploidy, strataN, harmN, Ho) {
    .Call('strataGdevel_HsCalc', PACKAGE = 'strataGdevel', alleleFreq, ploidy, strataN, harmN, Ho)
}

Hstats_C <- function(loci, strata, ploidy) {
    .Call('strataGdevel_Hstats_C', PACKAGE = 'strataGdevel', loci, strata, ploidy)
}

getMaxInt <- function(x) {
    .Call('strataGdevel_getMaxInt', PACKAGE = 'strataGdevel', x)
}

table2D <- function(x, y) {
    .Call('strataGdevel_table2D', PACKAGE = 'strataGdevel', x, y)
}

rowSumC <- function(x) {
    .Call('strataGdevel_rowSumC', PACKAGE = 'strataGdevel', x)
}

colSumC <- function(x) {
    .Call('strataGdevel_colSumC', PACKAGE = 'strataGdevel', x)
}

colMeanC <- function(x) {
    .Call('strataGdevel_colMeanC', PACKAGE = 'strataGdevel', x)
}

outerC <- function(x, y) {
    .Call('strataGdevel_outerC', PACKAGE = 'strataGdevel', x, y)
}

intVecToMat <- function(x, ncol) {
    .Call('strataGdevel_intVecToMat', PACKAGE = 'strataGdevel', x, ncol)
}

numVecToMat <- function(x, ncol) {
    .Call('strataGdevel_numVecToMat', PACKAGE = 'strataGdevel', x, ncol)
}

calcStrataN <- function(locus, strata) {
    .Call('strataGdevel_calcStrataN', PACKAGE = 'strataGdevel', locus, strata)
}

statChi2_C <- function(loci, strata, ploidy) {
    .Call('strataGdevel_statChi2_C', PACKAGE = 'strataGdevel', loci, strata, ploidy)
}

alleleFreqCalc <- function(locVec, strata, ploidy) {
    .Call('strataGdevel_alleleFreqCalc', PACKAGE = 'strataGdevel', locVec, strata, ploidy)
}

prHetCalc <- function(alleles, nvec, locusMat, strata, ploidy) {
    .Call('strataGdevel_prHetCalc', PACKAGE = 'strataGdevel', alleles, nvec, locusMat, strata, ploidy)
}

varCompCalc <- function(nvec, alleleFreq, prHet, r, nbar, rnbar, nc) {
    .Call('strataGdevel_varCompCalc', PACKAGE = 'strataGdevel', nvec, alleleFreq, prHet, r, nbar, rnbar, nc)
}

statFst_C <- function(loci, strata, ploidy) {
    .Call('strataGdevel_statFst_C', PACKAGE = 'strataGdevel', loci, strata, ploidy)
}

statGst_C <- function(loci, strata, ploidy) {
    .Call('strataGdevel_statGst_C', PACKAGE = 'strataGdevel', loci, strata, ploidy)
}

statGstPrime_C <- function(loci, strata, ploidy, primeType) {
    .Call('strataGdevel_statGstPrime_C', PACKAGE = 'strataGdevel', loci, strata, ploidy, primeType)
}

statGstDblPrime_C <- function(loci, strata, ploidy) {
    .Call('strataGdevel_statGstDblPrime_C', PACKAGE = 'strataGdevel', loci, strata, ploidy)
}

statJostD_C <- function(loci, strata, ploidy) {
    .Call('strataGdevel_statJostD_C', PACKAGE = 'strataGdevel', loci, strata, ploidy)
}

