# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getMaxInt <- function(x) {
    .Call('strataGdevel_getMaxInt', PACKAGE = 'strataGdevel', x)
}

table2D <- function(x, y) {
    .Call('strataGdevel_table2D', PACKAGE = 'strataGdevel', x, y)
}

rowSumC <- function(x) {
    .Call('strataGdevel_rowSumC', PACKAGE = 'strataGdevel', x)
}

colSumC <- function(x) {
    .Call('strataGdevel_colSumC', PACKAGE = 'strataGdevel', x)
}

outerC <- function(x, y) {
    .Call('strataGdevel_outerC', PACKAGE = 'strataGdevel', x, y)
}

statChi2_C <- function(loci, strata) {
    .Call('strataGdevel_statChi2_C', PACKAGE = 'strataGdevel', loci, strata)
}

